Only use NIOSSL on macOS and Linux (#101)
adam-fowler/mqtt-nio pull request #102
Opened 2022-02-09 17:24 UTC by obriensp

When building for SwiftUI Previews, checking if `NIOSSL` is available will succeed, despite the package has been configured to only link on macOS and Linux. This results in link errors which break SwiftUI Previews.

2022-02-10 18:09 UTC, adam-fowler commented
Sorry been a bit slow to reply (I'm on holiday, until Monday). Your changes look fine although you shouldn't need the `canImport` if you add the platform checks. 

Also I would like to see the actual error myself before merging this though.

2022-02-10 18:36 UTC, obriensp commented
@adam-fowler No problem, and I hope you're having a great holiday!

For when you're back: I'm able to reproduce the issue using the EmCuTeeTee project in Xcode 13.2. I'll go ahead and update the conditionals to remove the `canImport`.

2022-02-14 13:16 UTC, adam-fowler requested changes
Hi, one other thing can you stick a comment above each change of the form "This should use canImport(NIOSSL), will change when it works with SwiftUI previews". 

Ignore the validity check, there is a problem with file headers and swift format which needs resolved

Otherwise LGTM

2022-02-15 17:20 UTC, adam-fowler approved these changes
LGTM

2022-02-15 19:24 UTC, merged